# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x0btransformer\"4\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\"x\n\x05State\x12,\n\x05items\x18\x01 \x03(\x0b\x32\x1d.transformer.State.ItemsEntry\x1a\x41\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.transformer.Tensor:\x02\x38\x01\"F\n\x12TransformerRequest\x12\r\n\x05op_id\x18\x01 \x01(\x05\x12!\n\x05state\x18\x02 \x01(\x0b\x32\x12.transformer.State\"W\n\x13TransformerResponse\x12\r\n\x05op_id\x18\x01 \x01(\x05\x12!\n\x05state\x18\x02 \x01(\x0b\x32\x12.transformer.State\x12\x0e\n\x06status\x18\x03 \x01(\t2b\n\x12TransformerService\x12L\n\x07Process\x12\x1f.transformer.TransformerRequest\x1a .transformer.TransformerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE_ITEMSENTRY']._loaded_options = None
  _globals['_STATE_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_TENSOR']._serialized_start=27
  _globals['_TENSOR']._serialized_end=79
  _globals['_STATE']._serialized_start=81
  _globals['_STATE']._serialized_end=201
  _globals['_STATE_ITEMSENTRY']._serialized_start=136
  _globals['_STATE_ITEMSENTRY']._serialized_end=201
  _globals['_TRANSFORMERREQUEST']._serialized_start=203
  _globals['_TRANSFORMERREQUEST']._serialized_end=273
  _globals['_TRANSFORMERRESPONSE']._serialized_start=275
  _globals['_TRANSFORMERRESPONSE']._serialized_end=362
  _globals['_TRANSFORMERSERVICE']._serialized_start=364
  _globals['_TRANSFORMERSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
